### ISSUE TITLE
javascriptDelay causing error

### ISSUE THREAD

**Issue by kbanman** [devongovett/node-wkhtmltopdf#11]
I'm trying to invoke the `--javascript-delay` parameter, like so:

```
wkhtmltopdf(html, { javascriptDelay: 500 }).pipe(stream);
```

It throws an error:

```
[Uncaught Exception] Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
```

**Comment by PyroSA** [comment]
I might be getting a similar issue on windows.

Args
```
'wkhtmltopdf',
'--quiet',
'--page-size',
'A4',
'--print-media-type',
'--footer-html',
'D:\\footer.html',
'--header-html',
'D:\\header.html',
'--replace',
{ toString: [Function: toString] },
'--javascript-delay',
100,
'-',
'D:\\pdf-file.pdf'
```

It then seemingly tries to use 100 as a resource:
```
Error: Failed loading page http://100 (sometimes it will work just to ignore this error with --load-error-handling ignore)

Exit with code 1 due to network error: HostNotFoundError]
```
