### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by NodeUrsa** [devongovett/node-wkhtmltopdf#112]
var rendered = "<h1>Test</h1><p>Hello world</p>";
		wkhtmltopdf(rendered, {
		    output: 'rendered.pdf',
		    pageSize: 'A4'
		});
then raise error like as below:

Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)

**Comment by ricksturgeon** [comment]
I have the same issue, tried several node versions now running node 8.9.1 with this error:Error: "write EPIPE
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)"
Code worked a year ago but either mac os or node is causing the wkhtmltopdf to fail, please help :) . Rick

**Comment by ricksturgeon** [comment]
Solved: The error is caused when you have not installed the command line version of wkhtmltopdf since this is just a wrapper. Simple error showed up when I turned on debug. Hope this is your issue above as well.

Rick

**Comment by crachuy-mdsol** [comment]
I got this when mishandling `stream` in the callback, even though I definitely have a working version of wkhtmltopdf on my path. Another error indicated there was nothing being sent back in the response. @NodeUrsa If that's your complete snippet, you may just need to send the PDF file you've created. You could also first verify it is in present on disk. Try something `const path = require('path')` and `res.sendFile(path.resolve('rendered.pdf'))`

**Comment by rahrang** [comment]
i had the same problem. fixed it with @ricksturgeon's advice, downloading the command line version  from https://wkhtmltopdf.org/downloads.html#stable.

**Comment by bouchja1** [comment]
You will get this error also if you are using wkhtmltopdf v0.13 alpha.

**Comment by krushndayshmookh** [comment]
> i had the same problem. fixed it with @ricksturgeon's advice, downloading the command line version from https://wkhtmltopdf.org/downloads.html#stable.

thanks

**Comment by prabhurajshell** [comment]
Still facing this on Mac. Command Line version is downloaded. - wkhtmltopdf 0.12.6 (with patched qt) 

Any ideas on how to resolve this?
