### ISSUE TITLE
Spawn Error

### ISSUE THREAD

**Issue by Samerkassem** [devongovett/node-wkhtmltopdf#127]
I have: 

    this.wkhtmltopdf = async function () {
        try {
            console.log("createpdf")
            var response = await $http({
                url: '/wkhtmltopdf',
                method: "POST",
                responseType: 'blob',
                data:{"b":"XXX"}
            });
    
            if (response.status != 200) {
                this.message = this.gs("downloadFailed", "There was an error downloading the file");
                return;
            }
    
            var blob = new Blob([response.data], { type: 'application/*' });
            saveAs(blob, 'test.pdf');
        } catch (err) {
            $window.alert('There was an error in getting the file');
        }
    };

It is installed in package:

    "wkhtmltopdf": "^0.3.4"
  

I have installed the tool from their official website as recommended by SO users in other threads, and in the official npm:
https://www.npmjs.com/package/wkhtmltopdf

From  https://wkhtmltopdf.org/downloads.html#stable

I have this PATH in my environment variables, both User and System vars [![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/OSvep.png

And STILL getting this error on my machine, but on cloud it's working:

    C:\Users\Samer\Desktop\ALL fineon projects\azure-fineon-webapp-fo\node_modules\wkhtmltopdf\index.js:161
        throw new Error(err); // critical error
        ^
    
    Error: Error: spawn wkhtmltopdf ENOENT
        at ChildProcess.<anonymous> (C:\Users\xxx\Desktop\ALL xxprojects\azure-xx-webapp-fo\node_modules\wkhtmltopdf\index.js:161:11)
        at Object.onceWrapper (events.js:286:20)
        at ChildProcess.emit (events.js:198:13)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
        at onErrorNT (internal/child_process.js:415:16)

So what else to do?

**Comment by Domuska** [comment]
I ran into the very same issue. Looking at the older discussion in here, a very hacky workaround (I guess okay for very short term if you're doing development on windows machine) is to do what's described here (https://github.com/devongovett/node-wkhtmltopdf/issues/29).

In a nutshell, you can change the node_modules/wkhtmltopdf/index.js the variable `wkhtmltopdf.command` to be the full path to the executable binary instead of just attempting to spawn `wkhtmltopdf`. This could be fixed in a much smarter way on the library side, but if this is blocking your work temporarily that's at least a workaround.

**Comment by yurks** [comment]
https://github.com/devongovett/node-wkhtmltopdf/pull/133 will stop process termination in such cases
