### ISSUE TITLE
QSSlScoket error

### ISSUE THREAD

**Issue by Philmod** [devongovett/node-wkhtmltopdf#28]
Hey bud,

Here is an error appearing when we use this module:
```
Oct 22 20:12:08 - ERROR - uncaughtException - Error: QSslSocket: cannot resolve SSLv2_client_method
    at Socket.<anonymous> (/opt/webapp/node_modules/wkhtmltopdf/index.js:79:17)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at Pipe.onread (net.js:528:21)
```

I think it's just a warning tho.

**Comment by zxlin** [comment]
If it's just a warning, latest commit fixes the issue by giving a options.ignore to suppress warnings.
