### ISSUE TITLE
Supress sRGB profile error

### ISSUE THREAD

**Issue by bnvk** [devongovett/node-wkhtmltopdf#56]
Using this module with `wkhtmltopdf` on Fedora 21, the following error surfaces

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
    at Socket.<anonymous> (/home/user/Conjuror/node_modules/wkhtmltopdf/index.js:79:17)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at Pipe.onread (net.js:529:21)
```

However, the PDF seems to be generated just fine and dandy. Seems like this should maybe be supressed.

**Comment by zxlin** [comment]
Latest commit offers an ignore key in options to suppress warnings, see the README for usage.
