### ISSUE TITLE
cat not found on Mac when processing an URL

### ISSUE THREAD

**Issue by pacofr** [devongovett/node-wkhtmltopdf#72]
Hello,
I've upgraded from a very old version to the latest version 0.3.1 of node-wkhtmltopdf on my Mac (OS X El Capitan 10.11.4), and now when i execute this command:

`wkhtmltopdf("https://www.google.com", {debug:1}).pipe(res);`

It generates the error:

`[node-wkhtmltopdf] [debug] /bin/bash: cat: command not found`

and the pdf cannot be retrieved.

It seems that `/bin/sh` was changed to `/bin/bash`  few versions ago and it looks to have broken the Mac support. Note that my "old" version of node-wkhtmltopdf was correctly working before.

Quick fix would just to update this portion of code with darwin platform: 

````
if (process.platform === 'win32') {
    var child = spawn(args[0], args.slice(1));
  } else if (process.platform === 'darwin') {
    // Mac support
    var child = spawn('/bin/sh', ['-c', args.join(' ') + ' | cat ; exit ${PIPESTATUS[0]}']);
  }else{
    // this nasty business prevents piping problems on linux
    // The return code should be that of wkhtmltopdf and not of cat
    // http://stackoverflow.com/a/18295541/1705056
    var child = spawn('/bin/bash', ['-c', args.join(' ') + ' | cat ; exit ${PIPESTATUS[0]}']);
  }
````

Thank you!

**Comment by zxlin** [comment]
Do you know which version did you upgrade from?

**Comment by pacofr** [comment]
It was 0.1.5.

**Comment by zxlin** [comment]
can you check out the [issue72](https://github.com/devongovett/node-wkhtmltopdf/tree/issue72) branch and confirm that the changes work?

**Comment by pacofr** [comment]
tested and working. Thank you

**Comment by pacofr** [comment]
I've just noticed that some linux distribution does not support /bin/bash at all, but only /bin/sh like http://www.alpinelinux.org/ or https://coreos.com/ (and of course those are the ones we are using for deployment) so the current solution might not be best one for those kind of specific linux.

**Comment by zxlin** [comment]
I added an option `wkhtmltopdf.shell` for now so you can specify what shell to use. 
I don't exactly recall why I switched to bash instead of sh. It may have been someone's PR that they didn't rebase, so I just did it real quick. 

I'm thinking that I should look into a postinstall script that will detect what distro you're running and set that option for you.

**Comment by pacofr** [comment]
> I don't exactly recall why I switched to bash instead of sh.

I think it was for this : 
```
The return code should be that of wkhtmltopdf and not of cat
 // http://stackoverflow.com/a/18295541/1705056
```

I just figured also that PIPESTATUS is not supported by sh, but only by bash.

Here is what we have currently when executing the lib on sh linux : 
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: /bin/sh: syntax error: **bad substitution**

wkhtmltopdf exited with code 2
    at handleError (/srv/current/api/node_modules/wkhtmltopdf/index.js:137:16)
    at ChildProcess.<anonymous> (/srv/current/api/node_modules/wkhtmltopdf/index.js:108:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

see http://superuser.com/questions/704460/how-do-you-use-pipestatus-tee-and-bin-sh-together

**Comment by zxlin** [comment]
Well that's unfortunate, I rolled back npm to 0.3.1 for now. Let's figure out how to solve this problem nicely instead of a duct tape. 

Just to verify, you're using the standard `sh` builtin to Mac right and Mac works fine?

**Comment by pacofr** [comment]
I've fork the repo and will try to find a solution too

**Comment by tlycken** [comment]
@zxlin @pacofr I'm running into this problem now (`syntax error: bad substitution`) when running this package under Alpine Linux - did you ever find a solution and/or workaround for the problems?

I've tried with `wkhtmltopdf.shell = '/bin/sh'` as well as with `wkhtlmtopdf.shell = /bin/ash`, but to no avail.
